// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5XCGVohLbVG_tcmga5Zn1au_GeHwUwTo',
    appId: '1:1057135737184:web:c845050790f9afc3f80605',
    messagingSenderId: '1057135737184',
    projectId: 'movilies',
    authDomain: 'movilies.firebaseapp.com',
    storageBucket: 'movilies.appspot.com',
    measurementId: 'G-YDBGYDSZJY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKUMFg9fEKFVwsgoSKekRcbBMuER5bQw8',
    appId: '1:1057135737184:android:a48dc353d3fd993af80605',
    messagingSenderId: '1057135737184',
    projectId: 'movilies',
    storageBucket: 'movilies.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEaMJd0BBqTpOsHPQyos7bwlGm5ntv_RM',
    appId: '1:1057135737184:ios:f311402537acbf4af80605',
    messagingSenderId: '1057135737184',
    projectId: 'movilies',
    storageBucket: 'movilies.appspot.com',
    iosClientId: '1057135737184-42sr4gjd50jjb6ojblt00ddmlahfe2f2.apps.googleusercontent.com',
    iosBundleId: 'com.example.movilies',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEaMJd0BBqTpOsHPQyos7bwlGm5ntv_RM',
    appId: '1:1057135737184:ios:f311402537acbf4af80605',
    messagingSenderId: '1057135737184',
    projectId: 'movilies',
    storageBucket: 'movilies.appspot.com',
    iosClientId: '1057135737184-42sr4gjd50jjb6ojblt00ddmlahfe2f2.apps.googleusercontent.com',
    iosBundleId: 'com.example.movilies',
  );
}
